# Generated by Django 2.0.2 on 2018-10-30 12:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_high_risk', models.BooleanField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tv', models.CharField(max_length=12)),
                ('date_time', models.DateTimeField()),
                ('spread', models.FloatField()),
                ('is_game_of_week', models.BooleanField(default=False)),
                ('underdog_score', models.IntegerField(blank=True, null=True)),
                ('favorite_score', models.IntegerField(blank=True, null=True)),
                ('is_tie_breaker', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown', max_length=128)),
                ('upload_date', models.DateTimeField()),
                ('file', models.FileField(default=None, upload_to='', validators=[django.core.validators.FileExtensionValidator(['xlsx'])])),
            ],
            options={
                'ordering': ['upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('end', models.DateTimeField()),
                ('name', models.CharField(max_length=128)),
                ('start', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='favorite_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_id', to='pool.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_id', to='pool.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='underdog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underdog_id', to='pool.Team'),
        ),
        migrations.AddField(
            model_name='bet',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.Game'),
        ),
        migrations.AddField(
            model_name='bet',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.Team'),
        ),
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
