# Generated by Django 2.0.5 on 2018-10-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
