# Generated by Django 2.0.5 on 2018-10-21 14:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pool', '0002_remove_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingBet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bet_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BettingLine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('line_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BettingPlayer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('betting_line_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pool.BettingLine')),
            ],
        ),
        migrations.CreateModel(
            name='BettingRoster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 10, 21, 14, 16, 20, 934480, tzinfo=utc))),
                ('team_name', models.CharField(max_length=128)),
                ('rival_name', models.CharField(max_length=128)),
                ('is_favorite', models.BooleanField()),
                ('is_underdog', models.BooleanField()),
                ('is_home_team', models.BooleanField()),
                ('tv_station', models.CharField(max_length=10)),
                ('game_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='bettingplayer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bettingline',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bettingbet',
            name='betting_line_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pool.BettingLine'),
        ),
        migrations.AddField(
            model_name='bettingbet',
            name='roster_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pool.BettingRoster'),
        ),
    ]
