# Generated by Django 2.0.5 on 2018-10-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_auto_20181021_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bettingroster',
            name='date',
        ),
        migrations.AddField(
            model_name='bettingroster',
            name='is_game_of_the_week',
            field=models.BooleanField(default=False),
        ),
    ]
