# Generated by Django 2.1.1 on 2018-10-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_auto_20181030_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='user_id',
            new_name='user',
        ),
    ]
