# Generated by Django 2.1.1 on 2018-10-21 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pool', '0004_auto_20181021_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('is_high_risk', models.BooleanField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('favorite_id', models.IntegerField()),
                ('underdog_id', models.IntegerField()),
                ('home_id', models.IntegerField()),
                ('tv', models.CharField(max_length=12)),
                ('date_time', models.DateTimeField()),
                ('spread', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='bettingbet',
            name='betting_line_id',
        ),
        migrations.RemoveField(
            model_name='bettingbet',
            name='roster_id',
        ),
        migrations.RemoveField(
            model_name='bettingline',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='bettingplayer',
            name='betting_line_id',
        ),
        migrations.RemoveField(
            model_name='bettingplayer',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='BettingBet',
        ),
        migrations.DeleteModel(
            name='BettingLine',
        ),
        migrations.DeleteModel(
            name='BettingPlayer',
        ),
        migrations.DeleteModel(
            name='BettingRoster',
        ),
        migrations.AddField(
            model_name='bet',
            name='game_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pool.Game'),
        ),
        migrations.AddField(
            model_name='bet',
            name='team_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pool.Team'),
        ),
        migrations.AddField(
            model_name='bet',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
