# Generated by Django 2.0.2 on 2018-10-23 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_auto_20181021_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='game',
            name='favorite_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_id', to='pool.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_id', to='pool.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='underdog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underdog_id', to='pool.Team'),
        ),
    ]
