# Generated by Django 2.1.2 on 2018-10-27 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0007_gameupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameupload',
            old_name='game_data',
            new_name='file',
        ),
        migrations.AddField(
            model_name='gameupload',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameupload',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
