# Generated by Django 2.1.1 on 2018-10-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0007_auto_20181030_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='end',
        ),
        migrations.RemoveField(
            model_name='season',
            name='start',
        ),
    ]
