# Generated by Django 2.1.1 on 2018-10-30 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0008_auto_20181030_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='end',
            field=models.DateField(default=datetime.date(2018, 10, 30)),
        ),
        migrations.AddField(
            model_name='season',
            name='start',
            field=models.DateField(default=datetime.date(2018, 10, 30)),
        ),
    ]
