# Generated by Django 2.1.1 on 2018-10-30 21:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0009_auto_20181030_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='end',
            field=models.DateField(default=datetime.datetime(2018, 10, 30, 21, 21, 7, 282756, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='season',
            name='start',
            field=models.DateField(default=datetime.datetime(2018, 10, 30, 21, 21, 7, 282756, tzinfo=utc)),
        ),
    ]
