# Generated by Django 2.1.1 on 2018-10-30 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0010_auto_20181030_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='season',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
