# Generated by Django 2.1.1 on 2018-10-29 23:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0011_auto_20181027_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.DateTimeField()),
                ('name', models.CharField(max_length=128)),
                ('start', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_team',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='amount',
        ),
        migrations.AddField(
            model_name='game',
            name='favorite_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_game_of_week',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='is_tie_breaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='underdog_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.Game'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.Team'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='spread',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gameupload',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['xlsx'])]),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
