# Generated by Django 2.1.3 on 2018-11-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0012_auto_20181104_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ['user', 'game', 'date_time']},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['date_time']},
        ),
    ]
